config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
	authenticate :user, -> (u) { u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end

	resources :friendships
	resources :reviews
	resources :skippers
	resources :users

	devise_for :users, controllers: {
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omniauth_callbacks: 'users/omniauth_callbacks',
		confirmations: 'users/confirmations',
		passwords: 'users/passwords'
	}, path_prefix: 'devise'

	get 'service-worker.js' => 'service_worker#service_worker'
	get 'manifest.json' => 'service_worker#manifest'

	root to: 'pages#index'
	get 'about' => 'pages#about'
	get 'contact' => 'pages#contact'
	post 'contact' => 'pages#send_contact'
	get 'privacy_policy' => 'pages#privacy_policy'
	get 'terms_of_service' => 'pages#terms_of_service'
	get 'invite' => 'pages#invite'
	post 'invite' => 'pages#send_invite'
	get 'offline' => 'pages#offline'

	get 'users/friends' => 'users#index_friends'
	post 'users/save_skipper/:skipper_id' => 'users#save_skipper', as: 'save_skipper'
	post 'users/unsave_skipper/:skipper_id' => 'users#unsave_skipper', as: 'unsave_skipper'
end

app/models/skipper.rb
# The Skipper class represents a human skipper, who employees those humans who create User accounts.
class Skipper < ApplicationRecord
	attribute :firstname, :firstname
	attribute :lastname, :lastname
	attribute :boatname, :boatname
	attribute :city
	attribute :state
	attribute :active, default: true
	attribute :creator_id
	attribute :populated, default: false

	belongs_to :creator, class_name: 'User', foreign_key: :creator_id
	has_many :reviews, dependent: :destroy

	# Add validations for presence of all of the above properties
	validates :firstname, :lastname, :boatname, presence: true

	validate :unique?

	def name
		"#{firstname} #{lastname}"
	end

	private

	def unique?
		skippers = Skipper.where(firstname:, lastname:, city:, state:)

		raise DuplicateRecordError if skippers.count > 1

		return if skippers.count.zero?

		skipper = skippers.first
		errors.add(:skipper_id, "named #{name} in #{city}, #{state} already exists") unless skipper.id == id
	end
end

app/controllers/skippers_controller.rb
class SkippersController < ApplicationController
	before_action :redirect_unless_logged_in
	before_action :set_skipper, only: %i[show edit update destroy]

	# GET /skippers or /skippers.json
	def index
		if (query = params[:q]).present?
			query_downcase = query.downcase

			@perfect_match_skippers = Skipper.where("(LOWER(firstname) || ' ' || LOWER(lastname)) LIKE ?||'%'", query_downcase)
			p 'HEY LOOK HERE'
			p @perfect_match_skippers
			pattern = helpers.sql_similar_to_from_query(query_downcase)
			loose_match_skippers = Skipper.where('LOWER(firstname) SIMILAR TO ?', pattern).or(
				Skipper.where('LOWER(lastname) SIMILAR TO ?', pattern).or(
					Skipper.where('LOWER(boatname) SIMILAR TO ?', pattern)
				)
			)

			@skippers = loose_match_skippers - @perfect_match_skippers
		else
			saved_skippers = current_user.saved_skippers
			@saved_skippers = saved_skippers unless saved_skippers.empty?
		end
	end

	# GET /skippers/1 or /skippers/1.json
	def show
		return unless current_user.reviewed_skipper?(@skipper)

		@review = Review.find_by(author_id: current_user.id, skipper_id: @skipper.id)
	end

	# GET /skippers/new
	def new
		@skipper = Skipper.new
	end

	# GET /skippers/1/edit
	def edit; end

	# POST /skippers or /skippers.json
	def create
		@skipper = Skipper.new(
			creator_id: current_user.id,
			**skipper_params
		)

		respond_to do |format|
			if @skipper.save
				format.html { redirect_to skipper_url(@skipper), notice: 'Skipper was successfully created.' }
				format.json { render :show, status: :created, location: @skipper }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @skipper.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /skippers/1 or /skippers/1.json
	def update
		respond_to do |format|
			if @skipper.update(skipper_params)
				format.html { redirect_to skipper_url(@skipper), notice: 'Skipper was successfully updated.' }
				format.json { render :show, status: :ok, location: @skipper }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @skipper.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /skippers/1 or /skippers/1.json
	def destroy
		@skipper.destroy

		respond_to do |format|
			format.html { redirect_to skippers_url, notice: 'Skipper was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_skipper
		@skipper = Skipper.find(params[:id])
	end

	# Only allow a list of trusted parameters through.
	def skipper_params
		puts permitted_params = params.fetch(:skipper, {}).permit(:firstname, :lastname, :boatname, :city, :state)
		permitted_params[:boatname] = helpers.sanitize_boatname(permitted_params[:boatname]) if permitted_params[:boatname]

		permitted_params
	end

	def skippers_params
		params.permit(:q)
	end
end

app/helpers/skippers_helper.rb
module SkippersHelper
    def color_for_skipper_flag(skipper, flag, intensity, is_good)
        reviews = skipper.reviews
        flagged_reviews = reviews.filter { |r| r.send(flag) }
        flag_proportion = flagged_reviews.count / reviews.count

        bg_gray_100 = "f3f4f6"
        if is_good
            color = "#00ff00"
        else
            color = "#ff0000"
        end

        mix = interpolate_colors(bg_gray_100, color, flag_proportion)

        return interpolate_colors("#ffffff", mix, intensity.fdiv(1000))
    end

    def color_for_skipper(skipper)
        reviews = skipper.reviews
        return '#f5f5f5' if reviews.count < 3
        flagged_reviews = reviews.filter(&:bad_flags?)
        flag_proportion = flagged_reviews.count.fdiv(reviews.count)

        green = "#00ff00"
        red = "#ff0000"

        mix = interpolate_colors(green, red, flag_proportion)

        return interpolate_colors("#ffffff", mix, 0.1)
    end

    def sanitize_boatname(boatname)
        fv_match_data = boatname.match(/\s*[Ff]\/[Vv]\s*/)
        return boatname unless fv_match_data

        match_string = fv_match_data[0]
        no_fv_boatname = boatname.gsub(match_string, "")
        
        no_fv_boatname.titleize
    end

    def fv_boatname(boatname)
        "FV #{boatname}"
    end

    private

    def interpolate_colors(color_string_1, color_string_2, amount)
        raise BadArgumentError unless 0 <= amount && amount <= 1
        
        color_1_tuple = color_string_to_tuple(color_string_1)
        color_2_tuple = color_string_to_tuple(color_string_2)

        new_color_tuple = interpolate(color_1_tuple, color_2_tuple, amount)
        new_color_hex_tuple = new_color_tuple.map{|i| "%.2x" % i}
        new_color_hex = "##{new_color_hex_tuple.join}"

        return new_color_hex
    end

    def interpolate(iterable_1, iterable_2, amount)
        raise BadArgumentError unless 0 <= amount && amount <= 1

        diff_iterable = iterable_2.map.with_index { |entry, index| entry - iterable_1[index] }
        scaled_diff_iterable = diff_iterable.map {|e| e * amount}

        return iterable_1.map.with_index { |entry, index| entry + scaled_diff_iterable[index] }
    end

    def color_string_to_tuple(color_string)
        return color_string[1,6].chars.each_slice(2).map(&:join).map{ |s| s.to_i(16) }
    end
end

app/views/skippers/_form.html.erb
<%= form_with(model: skipper, class: "contents") do |form| %>
  <%= render 'shared/errors', resource: skipper %>
  <div class='flex flex-col justify-start gap-6'>
    <div class='flex flex-col lg:flex-row lg:items-center gap-3'>
      <%= form.label :firstname, 'First name' %>
      <%= form.text_field :firstname %>
    </div>
    <div class='flex flex-col lg:flex-row lg:items-center gap-3'>
      <%= form.label :lastname, 'Last name' %>
      <%= form.text_field :lastname %>
    </div>
    <div class='flex flex-col lg:flex-row lg:items-center gap-3'>
      <%= form.label :boatname, "Boat name (exclude F/V)" %>
      <%= form.text_field :boatname %>
    </div>
		<div class='flex flex-col lg:flex-row gap-6'>
			<%= form.label :city, 'City' %>
      <%= form.text_field :city %>
		</div>
		<div class='flex flex-col lg:flex-row lg:items-center gap-3'>
      <%= form.label :state, "State" %>
      <%= form.select :state, options_for_select(Places::STATES.map { |state_double| state_double[1] }, skipper.state || 'AK') %>
    </div>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-100 text-lg cursor-pointer" %>
  </div>
<% end %>

app/views/skippers/_save_skipper.html.erb
<%= turbo_frame_tag :save_skipper, class: 'flex flex-col' do %>
	<%= render 'shared/button/form',
			title: "Save #{@skipper.firstname}",
			method: :post,
			path: save_skipper_path(@skipper),
			data: { turbo_frame: :save_skipper },
			twcss_color: 'bg-blue-100'
	%>
<% end %>

app/views/skippers/_skipper.html.erb
<%= link_to skipper, data: { turbo: "false" } do %>
  <div id="<%= dom_id skipper %>" class='flex flex-row'>
    <div id="<%= dom_id skipper %>" class='flex flex-col max-sm:w-full xl:flex-row rounded-lg p-5 xl:px-8 xl:gap-16 xl:items-center items-start' style="background-color: <%= color_for_skipper(skipper) %>;">
      <h4 class='font-bold pb-3 lg:pb-5 xl:pb-0'><%= skipper.name %></h3>
      <h4><%= fv_boatname(skipper.boatname) %></h3>
      <% if skipper.city %>
        <h4><%= skipper.city %>, <%= skipper.state %></h4>
      <% end %>
    </div>
  </div>
<% end %>

app/views/skippers/_unsave_skipper.html.erb
<%= turbo_frame_tag :save_skipper, class: 'flex flex-col' do %>
	<%= render 'shared/button/form',
			title: "Unsave #{@skipper.firstname}",
			method: :post,
			path: unsave_skipper_path(@skipper),
			data: { turbo_frame: :save_skipper },
			twcss_color: 'bg-red-100'
	%>
<% end %>

app/views/skippers/edit.html.erb
<div class='flex flex-col w-full gap-10'>
  <div class='flex flex-row'>
    <%= render 'shared/button/link', title: 'Back to skipper', path: @skipper, twcss_color: 'bg-gray-100' %>
  </div>
  <h1 class='font-bold text-4xl py-5'>Editing Skipper</h1>
  <%= render 'form', skipper: @skipper %>
</div>

app/views/skippers/index.html.erb
<div class="flex flex-col gap-10">
  <h1>Skippers</h1>
  <%= render 'shared/searchbar', stimulus_action: 'search_skippers', path: skippers_path, title: 'Find or review a skipper' %>
  <%= turbo_frame_tag :search_results do %>
    <div id="skippers" class='flex flex-col gap-16'>
			<% unless @perfect_match_skippers.nil? %>
				<% unless @perfect_match_skippers.empty? %>
					<div id='perfect-match-skippers' class='flex flex-col gap-5'>
						<%= render @perfect_match_skippers %>
					</div>
				<% end %>
				<div class='flex flex-row justify-start'>
					<div class='flex flex-col gap-2 items-start'>
						<p>Don't see your skipper? Add them!</p>
						<%= render 'shared/button/link', title: 'Add your skipper', path: new_skipper_path, twcss_color: 'bg-blue-100', data: {turbo: false} %>
					</div>
				</div>
			<% end %>
      <% if @skippers.present? %>
				<div id='similar-match-skippers' class='flex flex-col gap-5'>
					<h3>Similar serach results</h3>
          <%= render @skippers %>
				</div>
			<% end %>
      <% if @saved_skippers.nil? %>
        <div class='flex flex-row'>
          <div class='flex flex-col gap-10'>
            <p>Your saved skippers will appear here.</p>
          </div>
        </div>
      <% else %>
				<%= render @saved_skippers %>
			<% end %>
    </div>
  <% end %>
</div>

app/views/skippers/new.html.erb
<div class="flex flex-col gap-10">
    <div class='flex flex-row'>
      <%= render 'shared/button/link', title: 'Skippers', path: skippers_path, twcss_color: 'bg-gray-100' %>
    </div>
  <h1 class="font-bold text-4xl">New skipper</h1>
  <%= render "form", skipper: @skipper %>
</div>

app/views/skippers/show.html.erb
<div class='flex flex-col gap-16'>
  <div class='flex flex-row'>
      <%= render 'shared/button/link', title: 'Skippers', path: skippers_path, twcss_color: 'bg-gray-100' %>
  </div>

	<div class='flex flex-row justify-between'>
		<div class='flex flex-col gap-3'>
			<h1><%= @skipper.name %></h1>
			<h3 class='text-2xl'><%= fv_boatname(@skipper.boatname) %></h3>
			<% if @skipper.city && @skipper.state %>
				<h3 class='text-2xl'><%= @skipper.city %>, <%= @skipper.state %></h3>
			<% end %>
		</div>

		<div class='flex flex-col'>
			<% if current_user.saved_skipper?(@skipper) %>
				<%= render 'skippers/unsave_skipper' %>
			<% else %>
				<%= render 'skippers/save_skipper' %>
			<% end %>
		</div>
	</div>

  <% if current_user.can_edit_or_delete_skipper?(@skipper) %>
    <div class='flex flex-row items-end justify-end gap-3'>
      <% if current_user.can_edit_skipper?(@skipper) %>
        <%= render 'shared/button/link', title: "Edit #{@skipper.firstname}", path: edit_skipper_path(@skipper), twcss_color: 'bg-yellow-100'%>
      <% end %>
      <% if current_user.can_delete_skipper?(@skipper) %>
        <%= render 'shared/button/form', title: "Delete #{@skipper.firstname}", path: @skipper, method: :delete, twcss_color: 'bg-red-100', data: {turbo_confirm: 'Are you sure? This action is permanent!'} %>
      <% end %>
    </div>
  <% end %>

  <div class='flex flex-col gap-5'>
    <div class='flex flex-row justify-between items-center'>
      <h2>Reviews</h2>
      <% if @review %>
        <%= render 'shared/button/link', title: 'Edit My Review', path: edit_review_path(@review), twcss_color: 'bg-yellow-100' %>
      <% else %>
        <%= render 'shared/button/link', title: "Review #{@skipper.firstname}", path: new_review_path(review: {skipper_id: @skipper.id}), twcss_color: 'bg-blue-100' %>
      <% end %>
    </div>
		
    <% if @skipper.reviews.present? %>
      <%= render @skipper.reviews %>
    <% else %>
      <p><%= @skipper.firstname %> has not yet been reviewed.</p>
    <% end %>
  </div>
</div>