config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
	authenticate :user, -> (u) { u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end

	resources :friendships
	resources :reviews
	resources :skippers
	resources :users

	devise_for :users, controllers: {
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omniauth_callbacks: 'users/omniauth_callbacks',
		confirmations: 'users/confirmations',
		passwords: 'users/passwords'
	}, path_prefix: 'devise'

	get 'service-worker.js' => 'service_worker#service_worker'
	get 'manifest.json' => 'service_worker#manifest'

	root to: 'pages#index'
	get 'about' => 'pages#about'
	get 'contact' => 'pages#contact'
	post 'contact' => 'pages#send_contact'
	get 'privacy_policy' => 'pages#privacy_policy'
	get 'terms_of_service' => 'pages#terms_of_service'
	get 'invite' => 'pages#invite'
	post 'invite' => 'pages#send_invite'
	get 'offline' => 'pages#offline'

	get 'users/friends' => 'users#index_friends'
	post 'users/save_skipper/:skipper_id' => 'users#save_skipper', as: 'save_skipper'
	post 'users/unsave_skipper/:skipper_id' => 'users#unsave_skipper', as: 'unsave_skipper'
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
	devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]

	attribute :firstname, :firstname
	attribute :lastname, :lastname
	attribute :email, :string
	attribute :phantom, :boolean, default: false
	attribute :admin, :boolean, default: false

	validates :firstname, :lastname, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: Devise.email_regexp }

	has_many :created_skippers, class_name: 'Skipper', foreign_key: :creator_id, dependent: :nullify
	has_many :authored_reviews, class_name: 'Review', foreign_key: :author_id, dependent: :destroy
	has_many :added_friendships, class_name: 'Friendship', foreign_key: :friend_id, dependent: :destroy

	scope :confirmed, -> { where.not(confirmed_at: nil) }

	def self.from_omniauth(auth)
		name_split = auth.info.name.split(' ')
		user = User.where(email: auth.info.email).first
		user ||= User.create!(
			provider: auth.provider,
			uid: auth.uid,
			firstname: name_split[0],
			lastname: name_split[1],
			email: auth.info.email,
			password: Devise.friendly_token[0, 20],
			confirmed_at: DateTime.now
		)
		user
	end

	# Actions

	def request_friendship_with!(user)
		if friendship_with?(user)
			# If request is duplicate, complain unless sender previously rejected recipient.
			unless Friendship.find_by(user_id: user.id, friend_id: id)&.status == Friendships::Statuses::REJECTED
				raise AlreadyExistsError
			end
		end

		Friendship.create!(user_id: id, friend_id: user.id)
	end

	def accept_friend_request!(friendship)
		friendship.update!(status: Friendships::Statuses::ACCEPTED)
	end

	def reject_friend_request!(friendship)
		friendship.update!(status: Friendships::Statuses::REJECTED)
	end

	def create_skipper!(skipper_params)
		Skipper.create!(creator_id: id, **skipper_params)
	end

	def delete_skipper!(skipper)
		raise UnauthorizedActionError unless can_delete_skipper?(skipper)

		skipper.delete
	end

	def save_skipper!(skipper)
		ensure_saved_skippers_key_exists_in_cache
		old_skipper_ids = saved_skipper_ids || []
		raise DuplicateRecordError if old_skipper_ids.include?(skipper.id)

		new_skipper_ids = old_skipper_ids.append(skipper.id)
		Rails.cache.write(saved_skippers_key, new_skipper_ids)
	end

	def unsave_skipper!(skipper)
		old_skipper_ids = saved_skipper_ids || []
		raise NoReferenceObjectError unless old_skipper_ids.include?(skipper.id)

		new_skipper_ids = old_skipper_ids.filter { |id| id != skipper.id }
		Rails.cache.write(saved_skippers_key, new_skipper_ids)
	end

	# Checks
	
	def can_edit_skipper?(skipper)
		skipper.creator_id == id || admin?
	end

	def can_delete_skipper?(skipper)
		skipper.creator_id == id || admin?
	end

	def can_edit_or_delete_skipper?(skipper)
		can_delete_skipper?(skipper) || can_edit_skipper?(skipper)
	end

	def reviewed_skipper?(skipper)
		authored_reviews.map(&:skipper_id).include?(skipper.id)
	end

	def wrote_review?(review)
		authored_reviews.map(&:id).include?(review.id)
	end

	def friendship_with?(user)
		users_in_friendship_sent_by_self = Friendship.where(user_id: id).map(&:friend)
		users_in_friendship_sent_to_self = Friendship.where(friend_id: id).map(&:user)

		users_in_friendship = users_in_friendship_sent_by_self | users_in_friendship_sent_to_self

		users_in_friendship.include?(user)
	end

	def friends_with?(user)
		friends.include?(user)
	end

	def pending_friends_with?(user)
		friendships.pending.map(&:friend).include?(user)
	end

	def rejected_friends_with?(user)
		friendships.rejected.map(&:friend).include?(user)
	end

	def saved_skipper?(skipper)
		saved_skippers.map(&:id).include?(skipper.id)
	end

	def verified?
		friends.count >= 2
	end

	# Reads

	def name
		"#{firstname} #{lastname}".titleize
	end

	def friendships
		friendships_sent_by_user = Friendship.accepted.where(user_id: id)
		friendships_sent_to_user = Friendship.accepted.where(friend_id: id)

		friendships_sent_by_user | friendships_sent_to_user
	end

	def pending_friendships
		Friendship.pending.where(friend_id: id)
	end

	def accepted_friendships
		Friendship.accepted.where(friend_id: id).or(Friendship.accepted.where(user_id: id))
	end

	def rejected_friendships
		Friendship.rejected.where(friend_id: id)
	end

	def friends
		friends_sent_by_user = Friendship.accepted.where(user_id: id).map(&:friend)
		friends_sent_to_user = Friendship.accepted.where(friend_id: id).map(&:user)

		friends_sent_by_user | friends_sent_to_user
	end

	def pending_friends
		pending_friendships.map(&:friend)
	end

	def accepted_friends
		accepted_friendships.map(&:friend)
	end

	def rejected_friends
		rejected_friendships.map(&:friend)
	end

	def saved_skipper_ids
		Rails.cache.read(saved_skippers_key)
	end

	def saved_skippers_key
		"user-#{id}-saved-skippers"
	end

	def saved_skippers
		ensure_saved_skippers_key_exists_in_cache
		saved_skipper_ids.map { |id| Skipper.find(id) }
	end

	# Method Overrides

	def send_devise_notification(notification, *args)
		if ENV['RAILS_ENV'] == 'test'
			devise_mailer.send(notification, self, *args)
		else
			devise_mailer.send(notification, self, *args).deliver_later
		end
	end

	private

	def ensure_saved_skippers_key_exists_in_cache
		Rails.cache.write(saved_skippers_key, []) unless Rails.cache.exist?(saved_skippers_key)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
	# GET /resource/confirmation/new
	# def new
	#   super
	# end

	# POST /resource/confirmation
	# def create
	#   super
	# end

	# GET /resource/confirmation?confirmation_token=abcdef
	def show
		super do
			sign_in(resource) if resource.errors.empty?
		end
	end

	# protected

	# The path used after resending confirmation instructions.
	# def after_resending_confirmation_instructions_path_for(resource_name)
	#   super(resource_name)
	# end

	# The path used after confirmation.
	def after_confirmation_path_for(_resource_name, resource)
		after_sign_in_path_for(resource)
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
		@user = User.from_omniauth(auth)
		if @user.persisted?
			sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
			# I don't want the flash messages in here, but I don't want to forget about this 'is_navigational_format?' method.
			# set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
			redirect_to new_user_registration_url
		end
	end

	def google_oauth2
		# @user = User.from_google(from_google_params)
		puts 'Yo let\'s check this all out PROFILE'
		puts auth.info.profile
		@user = User.from_omniauth(auth)

		if @user.persisted?
			# sign_out_all_scopes
			# flash[:notice] = t 'devise.omniauth_callbacks.success', kind: 'Google'
			sign_in_and_redirect @user, event: :authentication
		else
			flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
			redirect_to new_user_registration_url
		end
	end

	#  def from_google_params
	#    @from_google_params ||= {
	#      uid: auth.uid,
	#      email: auth.info.email
	#    }
	#  end

	def auth
		@auth ||= request.env['omniauth.auth']
	end

	def failure
		redirect_to root_path
	end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
	skip_after_action :discard_flash_notices, only: %i[create]
	# GET /resource/password/new
	# def new
	#   super
	# end

	# POST /resource/password
	def create
		if (user = User.find_by(email: params[:user][:email])) && !user.provider.nil?
			flash[:alert] = "The user associated with this email address logs in with #{helpers.display_omniauth_provider(user.provider)}."
			redirect_to new_user_password_path, status: :see_other
			return
		end
		super
	end

	# GET /resource/password/edit?reset_password_token=abcdef
	# def edit
	#   super
	# end

	# PUT /resource/password
	# def update
	#   super
	# end

	# protected

	# def after_resetting_user_password_path_for(resource) # If implementation of this ever throws an error, add 'user' before 'password' in the method definition, and try again
	#   super(resource)
	# end

	# # The path used after sending reset password instructions
	# def after_sending_reset_user_password_instructions_path_for(resource_name) # If implementation of this ever throws an error, add 'user' before 'password' in the method definition, and try again
	#   super(resource_name)
	# end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
	before_action :configure_sign_up_params, only: %i[create]
	before_action :configure_account_update_params, only: %i[update]
	skip_after_action :discard_flash_notices, only: %i[create]
	# GET /resource/sign_up
	# def new
	#   super
	# end

	# POST /resource
	# def create
	# 	super
	# end

	# GET /resource/edit
	# def edit
	#   super
	# end

	# PUT /resource
	# def update
	#   super
	# end

	# DELETE /resource
	# def destroy
	#   super
	# end

	# GET /resource/cancel
	# Forces the session data which is usually expired after sign
	# in to be expired now. This is useful if the user wants to
	# cancel oauth signing in/up in the middle of the process,
	# removing all OAuth session data.
	# def cancel
	#   super
	# end

	protected

	# If you have extra params to permit, append them to the sanitizer.
	def configure_sign_up_params
		devise_parameter_sanitizer.permit(:sign_up, keys: %i[firstname lastname])
	end

	# If you have extra params to permit, append them to the sanitizer.
	def configure_account_update_params
		devise_parameter_sanitizer.permit(:account_update, keys: %i[firstname lastname])
	end

	# The path used after sign up.
	# def after_sign_up_path_for(resource)
	# 	super(resource)
	# end

	# The path used after sign up for inactive accounts.
	# def after_inactive_sign_up_path_for(resource)
	# 	super(resource)
	# end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  after_action :clear_flash_notices, only: %i[create destroy]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  private

  def clear_flash_notices
    flash.discard(:notice)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :redirect_unless_logged_in
	before_action :set_user, only: %i[show edit update destroy]

	# GET /users or /users.json
	def index
		return unless (query = params[:q]).present?

		query_downcase = query.downcase
		pattern = helpers.sql_similar_to_from_query(query_downcase)

		@users = User.confirmed.where('LOWER(firstname) SIMILAR TO ?', pattern).or(
			User.confirmed.where('LOWER(lastname) SIMILAR TO ?', pattern)
		)
	end

	# def index_friends
	# 	user_id = params[:user_id]
	# 	friendship_type = params[:friendship_type]

	# 	case friendship_type
	# 	when :accepted
	# 		@users = User.find(user_id).friends
	# 	when :pending
	# 		raise AccessDeniedError unless user_id == current_user.id

	# 		@users = User.find(user_id).pending_friends
	# 	when :rejected
	# 		raise AccessDeniedError unless user_id == current_user.id

	# 		@users = User.find(user_id).rejected_friends
	# 	else
	# 		raise BadRequestError
	# 	end

	# 	return unless (q = params[:q]).present?

	# 	tokens = q.downcase.split(' ')
	# 	pattern = "%(#{tokens.join('|')})%"
	# 	@users = @users.where('LOWER(firstname) SIMILAR TO ?', pattern).or(
	# 		User.confirmed.where('LOWER(lastname) SIMILAR TO ?', pattern)
	# 	)
	# end

	# GET /users/1 or /users/1.json
	def show; end

	# GET /users/new
	def new
		@user = User.new
	end

	# GET /users/1/edit
	def edit; end

	# POST /users or /users.json
	def create
		@user = User.new(user_params)

		respond_to do |format|
			if @user.save
				format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: @user }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /users/1 or /users/1.json
	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /users/1 or /users/1.json
	def destroy
		@user.destroy

		respond_to do |format|
			format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def save_skipper
		@skipper = Skipper.find(saved_skippers_params[:skipper_id])
		current_user.save_skipper!(@skipper)

		render partial: 'skippers/unsave_skipper'
	end

	def unsave_skipper
		@skipper = Skipper.find(saved_skippers_params[:skipper_id])
		current_user.unsave_skipper!(@skipper)

		render partial: 'skippers/save_skipper'
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find(params[:id])
	end

	# Only allow a list of trusted parameters through.
	def user_params
		params.fetch(:user, {}).permit(:firstname, :lastname)
	end

	def saved_skippers_params
		params.permit(:skipper_id)
	end
end

# rubocop:enable Layout/IndentationStyle

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <%= render 'shared/errors', resource: user %>
  <div class='flex flex-col justify-start gap-6'>
    <div class='flex flex-row gap-3'>
      <%= form.label :first, "First Name" %>
      <%= form.text_field :firstname %>
    </div>
    <div class='flex flex-row gap-3'>
      <%= form.label :lastname, "Last Name" %>
      <%= form.text_field :lastname %>
    </div>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-100 text-lg cursor-pointer" %>
  </div>
<% end %>

app/views/users/_friends.html.erb
<div class='flex flex-col gap-5 xl:gap-10'>
    <div data-controller='friends' class='flex flex-row gap-3'>
        <button class='cursor-pointer buttonlike' data-action='click->friends#show_friends'>Friends</button>
        <button class='cursor-pointer buttonlike' data-action='click->friends#show_friend_requests'>Requests</button>
    </div>
    <div id='friends' class='flex flex-col gap-3 xl:gap-5'>
        <div class='flex flex-col gap-3 items-start'>
            <% if (friendships = @user.friendships).present? %>
                <%= render partial: 'friendships/friendship', collection: friendships, as: :friendship %>
            <% else %>
                <p class='text-light'>You don't have any friends yet. <%= link_to 'Find', users_path %> some now!</p>
            <% end %>
        </div>
    </div>
    <div id='friend-requests' class='flex flex-col gap-3 xl:gap-5 hidden'>
        <div class='flex flex-col gap-3 items-start'>
            <% if (pending_friendships = @user.pending_friendships).present? %>
                <%= render partial: 'friendships/pending_friendship', collection: pending_friendships, as: :friendship %>
            <% else %>
                <p class='text-light'>No friend requests.</p>
            <% end %>
        </div>
    </div>
</div>

app/views/users/_friendship_control.html.erb
<div class='flex flex-row items-center gap-3'>
	<% if !current_user.friendship_with?(@user) %>
		<%= render 'shared/button/form', title: 'Add Friend', path: friendships_path, method: :post, twcss_color: 'bg-blue-100', params: { friendship: {user_id: current_user.id, friend_id: @user.id}} %>
	<% elsif current_user.friends_with?(@user)%>
		<p class='py-3 px-5'>Friends!</p>
		<%= render 'shared/button/form', title: 'Remove Friend', path: friendships_path, method: :delete, twcss_color: 'bg-red-100', params: { friendship: {user_id: current_user.id, friend_id: @user.id}} %>	
	<% else %>
		<p class='py-3 px-5'>Friendship Pending</p>
		<%= render 'shared/button/form', title: 'Delete Request', path: friendships_path, method: :delete, twcss_color: 'bg-red-100', params: { friendship: {user_id: current_user.id, friend_id: @user.id}} %>
	<% end %>
</div>

app/views/users/_user.html.erb
<%= link_to user, data: { turbo: "false" } do %>
  <div id="<%= dom_id user %>" class='flex flex-row'>
    <div class='flex flex-col p-5 xl:px-8 xl:flex-row rounded-lg xl:gap-20 xl:items-center items-start bg-gray-100'>
      <h4 class='font-bold'><%= user.name %></h4>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="flex flex-col mx-auto w-full gap-16">
  <div class='flex flex-row'>
    <%= render 'shared/button/link', title: 'Back to user', path: @user, twcss_color: 'bg-gray-100' %>
  </div>
  <h1 class="font-bold text-4xl">Editing User</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div class="w-full flex flex-col gap-10">
  <h1 class="font-bold text-4xl">Users</h1>
  <%= render 'shared/searchbar', stimulus_action: 'search_users', path: users_path, title: 'Find a user' %>
  <div id="users" class='flex flex-col gap-5'>
    <%= turbo_frame_tag :search_results do %>
      <% if @users.present? %>
        <div id="users" class='flex flex-col gap-5'>
          <%= render @users %>
        </div>
      <% elsif !@users.nil? %>
        <div class='flex flex-row'>
          <div class='flex flex-col gap-10'>
            <p>We couldn't find any users matching your search. Would you like to <%= link_to 'send', invite_path, data: {turbo: false } %> someone an invite?</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="w-full">
  <h1>New user</h1>
  
  <%= render "form", user: @user %>

  <%= render 'shared/button/link', title: 'Users', path: users_path, twcss_color: 'bg-gray-100' %>
</div>

app/views/users/show.html.erb
<div class='flex flex-col gap-10'>
  <div class="flex flex-row">
    <%= render 'shared/button/link', title: 'Users', path: users_path, twcss_color: 'bg-gray-100' %>
  </div>
  <div class='flex flex-col gap-10'>
    <div>
      <h1><%= @user.name %></h1>
      <h3>Since <%= readable_datetime_month_year(@user.created_at) %></h3>
    </div>
    <div>
      <p class='text-2xl'><%= pluralize(@user.authored_reviews.count, 'review') %></p>
      <p class='text-2xl'><%= pluralize(@user.friends.count, 'friend') %></p>
    </div>
  <div class="w-full flex justify-end">
    <% if current_user == @user %>
      <div class='flex flex-col'>
        <div class="flex flex-row gap-3">
          <%= render 'shared/button/link', title: 'Edit', path: edit_user_path(@user), twcss_color: 'bg-yellow-100' %>
          <%= render 'shared/button/form', title: 'Delete', path: @user, method: :delete, twcss_color: 'bg-red-100', data: {turbo_confirm: 'Are you sure? This action is permanent!'} %>
        </div>
      </div>
    <% else %>
			<%= render 'users/friendship_control' %>
		<% end %>
  </div>
  <% if current_user == @user %>
    <%= render 'friends' %>
  <% end %>
  </div>
</div>