config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
	authenticate :user, -> (u) { u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end

	resources :friendships
	resources :reviews
	resources :skippers
	resources :users

	devise_for :users, controllers: {
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omniauth_callbacks: 'users/omniauth_callbacks',
		confirmations: 'users/confirmations',
		passwords: 'users/passwords'
	}, path_prefix: 'devise'

	get 'service-worker.js' => 'service_worker#service_worker'
	get 'manifest.json' => 'service_worker#manifest'

	root to: 'pages#index'
	get 'about' => 'pages#about'
	get 'contact' => 'pages#contact'
	post 'contact' => 'pages#send_contact'
	get 'privacy_policy' => 'pages#privacy_policy'
	get 'terms_of_service' => 'pages#terms_of_service'
	get 'invite' => 'pages#invite'
	post 'invite' => 'pages#send_invite'
	get 'offline' => 'pages#offline'

	get 'users/friends' => 'users#index_friends'
	post 'users/save_skipper/:skipper_id' => 'users#save_skipper', as: 'save_skipper'
	post 'users/unsave_skipper/:skipper_id' => 'users#unsave_skipper', as: 'unsave_skipper'
end

app/models/friendship.rb
# A Friendship indicates a 
class Friendship < ApplicationRecord
	attribute :user_id
	attribute :friend_id
	enum status: Friendships::Statuses.constants.map { |c| Friendships::Statuses.const_get c }.index_with(&:to_s), _default: Friendships::Statuses::PENDING

	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: :friend_id

	scope :pending, -> { where(status: Friendships::Statuses::PENDING) }
	scope :accepted, -> { where(status: Friendships::Statuses::ACCEPTED) }
	scope :rejected, -> { where(status: Friendships::Statuses::REJECTED) }

	def with_user(user_id)
		Friendship.where(user_id:).or(Friendship.where(friend_id: user_id))
	end

	def users
		Set[user, friend]
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :redirect_unless_logged_in
	before_action :set_friendship, only: %i[ show edit update destroy ]
	after_action :discard_flash_notices

	# GET /friendships or /friendships.json
	def index
		params = index_params
		raise BadArgumentError unless params[:for_user_id]

		case params[:friendships_type]
		when :accepted
			@friendships = Friendship.accepted.with_user(:for_user_id)
		when :pending
			@friendships = Friendship.pending.where(friend_id: :for_user_id)
		when :rejected
			@friendships = Friendship.rejected.where(friend_id: :for_usr_id)
		else
			raise BadArgumentError
		end
	end

	# GET /friendships/1 or /friendships/1.json
	def show; end

	# GET /friendships/new
	def new
		@friendship = Friendship.new
	end

	# GET /friendships/1/edit
	def edit; end

	# POST /friendships or /friendships.json
	def create
		params = friendship_params
		raise AlreadyExistsError if Friendship.find_by(user_id: params[:user_id], friend_id: params[:friend_id])

		@friendship = Friendship.new(**params, status: Friendships::Statuses::PENDING)

		respond_to do |format|
			if @friendship.save
				@user = User.find(params[:friend_id])
				format.html { redirect_to user_url(@user), notice: "Friendship was successfully created." }
				format.json { render :show, status: :created, location: @friendship }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @friendship.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /friendships/1 or /friendships/1.json
	def update
		respond_to do |format|
			if @friendship.update(friendship_params)
				format.html { redirect_to user_url(current_user), notice: "Friendship was successfully updated." }
				format.json { render :show, status: :ok, location: @friendship }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @friendship.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /friendships/1 or /friendships/1.json
	def destroy
		@friendship.destroy

		respond_to do |format|
			format.html { redirect_to current_user, notice: "Friendship was successfully destroyed." }
			format.json { head :no_content }
		end
	end

	private

	# Use callbacks to share common setup or constraints between actions.
	def set_friendship
		@friendship = Friendship.find(params[:id]) || Friendship.find_by(user_id: friendship_params[:user_id], friend_id: friendship_params[:friend_id])
	end

	# Only allow a list of trusted parameters through.
	def friendship_params
		params.fetch(:friendship, {}).permit(:user_id, :friend_id, :status)
	end

	def index_params
		params.permit(:for_user_id)
	end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, class: "contents") do |form| %>
  <%= render 'shared/errors' resource: friendship %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white text-lg cursor-pointer" %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
<% friend = [friendship.user, friendship.friend].filter{|u| u.id != current_user.id }[0] %>

<div class='flex flex-row gap-3 items-center w-full text-xs sm:text-sm md:text-base lg:text-lg;'>
		<div style='min-width: 24ch;'>
	    <%= render 'shared/button/link', title: friend.name, path: user_path(friend), twcss_color: 'transparent' %>
		</div>
    <%= render 'shared/button/form', title: 'Remove Friend', path: friendship_path(friendship), method: :delete, twcss_color: 'bg-red-100' %>
</div>

app/views/friendships/_pending_friendship.html.erb
<div class='flex flex-row gap-3 items-center p-5 bg-gray-100 rounded-lg'>
    <h3><%= friendship.user.name %> wants to be friends with you!</h3>
    <%= render 'shared/button/form', title: 'Accept', path: friendship_path(friendship), method: :put, twcss_color: 'bg-blue-100', params: {friendship: {status: Friendships::Statuses::ACCEPTED}} %>
    <%= render 'shared/button/form', title: 'Reject', path: friendship_path(friendship), method: :put, twcss_color: 'bg-blue-100', params: {friendship: {status: Friendships::Statuses::ACCEPTED}} %>
</div>

app/views/friendships/edit.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">Editing friendship</h1>

  <%= render "form", friendship: @friendship %>

  <%= render 'shared/button/link', title: 'Show this friendship', path: @friendship, twcss_color: 'bg-gray-100' %>
  <%= render 'shared/button/link', title: 'Friendships', path: friendships_path, twcss_color: 'bg-gray-100' %>
</div>

app/views/friendships/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Friendships</h1>
    <%= render 'shared/button/link', title: 'New friendship', path: new_friendship_path, twcss_color: 'bg-blue-100' %>
  </div>
  <div id="friendships" class="min-w-full">
    <%= render @friendships %>
  </div>
</div>

app/views/friendships/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">New friendship</h1>

  <%= render "form", friendship: @friendship %>

  <%= render 'shared/button/link', title: 'Friendships', path: friendships_path, twcss_color: 'bg-gray-100' %>
</div>

app/views/friendships/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <%= render @friendship %>
    <%= render 'shared/button/link', title: 'Edit this friendship', path: edit_friendship_path(@friendship), twcss_color: 'bg-gray-100' %>
    <div class="inline-block ml-2">
      <%= render 'shared/button/form', title: 'Destroy this friendship', path: @friendship, method: :delete, twcss_color: 'bg-gray-100' %>
    </div>
    <%= render 'shared/button/link', title: 'Friendships', path: friendships_path, twcss_color: 'bg-gray-100' %>
  </div>
</div>