config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
	authenticate :user, -> (u) { u.admin? } do
		mount Sidekiq::Web => '/sidekiq'
	end

	resources :friendships
	resources :reviews
	resources :skippers
	resources :users

	devise_for :users, controllers: {
		registrations: 'users/registrations',
		sessions: 'users/sessions',
		omniauth_callbacks: 'users/omniauth_callbacks',
		confirmations: 'users/confirmations',
		passwords: 'users/passwords'
	}, path_prefix: 'devise'

	get 'service-worker.js' => 'service_worker#service_worker'
	get 'manifest.json' => 'service_worker#manifest'

	root to: 'pages#index'
	get 'about' => 'pages#about'
	get 'contact' => 'pages#contact'
	post 'contact' => 'pages#send_contact'
	get 'privacy_policy' => 'pages#privacy_policy'
	get 'terms_of_service' => 'pages#terms_of_service'
	get 'invite' => 'pages#invite'
	post 'invite' => 'pages#send_invite'
	get 'offline' => 'pages#offline'

	get 'users/friends' => 'users#index_friends'
	post 'users/save_skipper/:skipper_id' => 'users#save_skipper', as: 'save_skipper'
	post 'users/unsave_skipper/:skipper_id' => 'users#unsave_skipper', as: 'unsave_skipper'
end

app/views/layouts/_footer.html.erb
<footer id='footer' class='flex flex-row justify-between items-end p-1 lg:p-2 bg-gray-100'>
    <ul id="footerLinks" class='max-md:grid max-md:grid-cols-2 max-md:gap-x-10 md:flex md:flex-row md:gap-5 items-start list-none'>
        <li class='flex flex-row items-center'><%= link_to "Home", root_path %></li>
        <li class='flex flex-row items-center'><%= link_to "Invite", invite_path %></li>
        <li class='flex flex-row items-center'><%= link_to "Contact", contact_path %></li>
        <li class='flex flex-row items-center'><%= link_to "About", about_path %></li>
        <li class='flex flex-row items-center'><%= link_to "Terms of Service", terms_of_service_path %></li>
        <li class='flex flex-row items-center'><%= link_to "Privacy Policy", privacy_policy_path %></li>
    </ul>
    <p class='text-sm text-light'>© 2023 Landho Dev, LLC</p>
</footer>

app/views/layouts/_navbar.erb
<header>
  <nav id='navbar' class="flex flex-row border-b-2 items-center gap-5 py-3 pl-3 pr-3 sm:pr-5 md:pr-8 md:pl-5">
    <%= link_to "/" do %>
      <img id='navbar-image' height='100%' src=<%= asset_path("buoy-small.png") %> />
    <% end %>
    <div class='flex flex-row <%= if current_user then 'justify-between' else 'justify-end' end %> w-full gap-3'>
      <% if current_user %>
        <div class='flex flex-row items-center gap-3 sm:gap-4 md:gap-5 flex-nowrap lg:items-center'>
          <%= link_to 'Skippers', skippers_path %>
          <%= link_to 'Users', users_path %>
        </div>
      <% end %>
      <div class='flex flex-row gap-3 sm:gap-4 md:gap-5 flex-nowrap items-center'>
        <% if current_user %>
          <%= link_to 'Profile', user_path(current_user) %>
          <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'block' %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path %>
          <%= link_to 'Log in', new_user_session_path %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='bg-blue-100'>
  <head>
    <title>Skipper Buoy</title>
    <meta name="facebook-domain-verification" content="8elt8n9u1cjm9fx87q3yxuxu4umblu" />

		<!-- PWA-related meta tags, manifest, and icons -->
    <meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" crossorigin="use-credentials" href="<%= asset_path('manifest.json') %>">
    <%= render 'shared/pwa_icons' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind.css", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body class='flex flex-col justify-between min-h-screen mx-auto bg-white' style="max-width: 1024px;">
    <div class='hidden' id="fb-root"></div>
    <!-- <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0&appId=1068800324527105&autoLogAppEvents=1" nonce="2rt3wZJJ"></script> -->
    <div class='flex flex-col'>
      <%= render 'layouts/navbar' %>
      <main class="flex flex-col gap-2 md:gap-3 lg:gap-5 pt-2 px-2 pb-16 md:pt-3 md:px-3 md:pb-22 lg:pt-5 lg:pb-28 lg:px-5">
          <%= render 'shared/flashes' %>
          <%= yield %>
      </main>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>